### ISSUE TITLE
Yaml string starting with % wrapping in quotes

### ISSUE THREAD

**Issue by brasileric** [DorsetDigital/silverstripe-cdnrewrite#10]
Hi,

In Silverstripe 4.7.0 it's required to wrap strings starting with % in quotes (in the yaml files). See: https://docs.silverstripe.org/en/4/changelogs/4.7.0/#support-for-symfony-4-components

Can you update this in the yaml file?

**Comment by DorsetDigital** [comment]
I thought I'd updated all of these... obviously missed one!
Thanks for the report, I'll push out a quick patch

**Comment by DorsetDigital** [comment]
This should now be fixed in a 2.0.1 release.

**Comment by brasileric** [comment]
so fast! Thanks a lot! :)
