### ISSUE TITLE
Disable for concept pages (suggestion)

### ISSUE THREAD

**Issue by brasileric** [DorsetDigital/silverstripe-cdnrewrite#9]
Hi,
Great module for using a cdn! 1 suggestion:

When a page is still in concept the cdn cannot pull the images yet. So when you view the page in stage mode you miss the images as the url's are already rewritten to the cdn url.

**Comment by DorsetDigital** [comment]
This is addressed in the v2.1.0 update.   A configuration variable has been added to enable manual enable / disable of the functionality in the preview window
